import type { Device } from '@/types';

export const DEVICES: Device[] = [
  {
    id: '1',
    name: 'Air Condition',
    icon: 'snow',
    status: 'Connected',
    isOn: true,
    kwhPerHour: 2,
    room: 'Master Bedroom',
    type: 'ac',
  },
  {
    id: '2',
    name: 'Lamp Light',
    icon: 'bulb-outline',
    status: 'Disconnected',
    isOn: false,
    kwhPerHour: 2,
    room: 'Master Bedroom',
    type: 'light',
  },
  {
    id: '3',
    name: 'Ceiling Fan',
    icon: 'aperture',
    status: 'Disconnected',
    isOn: false,
    kwhPerHour: 2,
    room: 'Edamame Bedroom',
    type: 'fan',
  },
  {
    id: '4',
    name: 'Homepod Mini',
    icon: 'radio',
    status: 'Disconnected',
    isOn: false,
    kwhPerHour: 2,
    room: 'Main Living Room',
    type: 'speaker',
  },
  {
    id: '5',
    name: 'CC Camera',
    icon: 'videocam-outline',
    status: 'Connected',
    isOn: true,
    kwhPerHour: 2,
    room: 'Main Living Room',
    type: 'camera',
  },
  {
    id: '6',
    name: 'Security Lock',
    icon: 'lock-closed-outline',
    status: 'Connected',
    isOn: true,
    kwhPerHour: 2,
    room: 'Master Bedroom',
    type: 'lock',
  },
];
